export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  PLAN_ITEM_NOT_FOUND: 'PLAN_ITEM_NOT_FOUND',
  BUDGET_EXCEEDED: 'BUDGET_EXCEEDED',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;
