export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  BOARD_ITEM_NOT_FOUND: 'BOARD_ITEM_NOT_FOUND',
  BOARD_CONFLICT: 'BOARD_CONFLICT',
  BUDGET_EXCEEDED: 'BUDGET_EXCEEDED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;
